# This is the main configuration file of your Dancer app
# env-related settings should go to environments/$env.yml
# all the settings in this file will be loaded at Dancer's startup.

# Your application's name
appname: "Agave Dancer"
#port: 3721

# The default layout to use for your application (located in
# views/layouts/main.tt)
layout: "main"

# when the charset is set to UTF-8 Dancer will handle for you
# all the magic of encoding and decoding. You should not care
# about unicode within your app when this setting is set (recommended).
charset: "UTF-8"

# template engine
# simple: default and very basic template engine
# template_toolkit: TT

session: 'YAML'
session_expires: '72 hr'
#session: 'Storable'
#session: 'cookie'
#session_cookie_key: '1{(b)a}sdf07234hjf0sdkflj12*&(@*az'
session_secure: 1
session_dir: '/tmp/dancer-sessions'

#template: "simple"
template: "template_toolkit"
engines:
  template_toolkit:
    encoding:  'utf8'
    start_tag: '[%'
    end_tag:   '%]'
    EVAL_PERL: 1
  JSON:
    convert_blessed: '1'
    allow_blessed: '1'

plugins:
  Ajax:
    content_type: 'application/json'
  Database:
    driver: 'mysql'
    database: 'sciapps'
    host: 'localhost'
    username: 'sciapps'
    password: 'mXPpA9ZM'
    on_connect_do: ["SET NAMES 'utf8'", "SET CHARACTER SET 'utf8'"]
    dbi_params:
      RaiseError: 1
      PrintError: 0
      PrintWarn:  0
      AutoCommit: 1

output_url:
  sciapps.org: 'https://data.sciapps.org/__path__'
  data.iplantcollaborative.org: 'https://agave.iplantc.org/files/v2/download/__owner__/system/__system__/__path__'
