# configuration file for production environment
port: 80

# only log warning and error messsages
log: "warning"

# log message to a file in logs/
logger: "file"

# don't consider warnings critical
warnings: 1

# hide errors 
show_errors: 1

# cache route resolution for maximum performance
route_cache: 1

# For debugging
#log: "core"
#logger: "console"
#warnings: 1
#show_errors: 1

# production config
agave_config: ".agave"
host_url: "https://www.sciapps.org"
archive_system: 'sciapps.org'
archive_home: '/agave_data'
archive_path: 'results'
input_system: 'brebiou.cshl.edu'
input_home: '/agave_data'
input_path: 'inputs'
email: 'noreply@sciapps.org'
upload_suffix: ".upload"
wf_step_prefix: 'wf_step_'
maxRunTime: "96:00:00"
datastore:
  __sorghumDB__: 
    system: 'sciapps.org'
    home: '/agave_data'
    path: 'data/sorghum'
  __maizecode__:
    system: 'sciapps.org'
    home: '/agave_data'
    path: 'data/maize'
  __public__:
    system: 'sciapps.org'
    home: '/agave_data'
    path: 'example_data'
  __system__:
    system: ''
    home: ''
    path: ''
  __output__:
    system: '1970491483740115431-242ac113-0001-007'
    home: ''
    path: 'example_data'
public_datastore_type: '__public__'
datastore_types: ['sorghumDB', 'maizecode', 'public']
uncompress_suffix: '.open.tar.gz'
use_file_server: 1
irodsEnvFile: '/usr/share/httpd/irodsEnv'
