# configuration file for production environment
port: 80

# only log warning and error messsages
log: "warning"

# log message to a file in logs/
logger: "file"

# don't consider warnings critical
warnings: 0

# hide errors 
show_errors: 0

# cache route resolution for maximum performance
route_cache: 1

# production config
agave_config: ".agave"
host_url: "http://www.sciapps.org/"
archive_system: 'brie.cshl.edu'
archive_path: 'results'
archive_home: '/agave_data'
input_system: 'brie.cshl.edu'
input_path: 'inputs'
input_home: '/agave_data'
output_url: 'http://data.sciapps.org'
email: 'noreply@sciapps.org'
upload_suffix: ".upload"
maxRunTime: "96:00:00"
datastore_system: 'data.sciapps.org'
uncompress_suffix: '.open.tar.gz'
