# configuration file for production environment
port: 80

# only log warning and error messsages
log: "warning"

# log message to a file in logs/
logger: "file"

# don't consider warnings critical
warnings: 1

# hide errors 
show_errors: 1

# cache route resolution for maximum performance
route_cache: 1

# For debugging
#log: "core"
#logger: "console"
#warnings: 1
#show_errors: 1

# production config
agave_config: ".agave"
host_url: "https://www.sciapps.org"
archive_system: 'sciapps.org'
archive_home: '/agave_data'
archive_path: 'results'
email: 'noreply@sciapps.org'
upload_suffix: ".upload"
wf_step_prefix: 'wf_step_'
maxRunTime: "96:00:00"
defaultUser: 'maizecode'
datastore:
  __home__:
    system: 'data.iplantcollaborative.org'
    home: '/iplant/home'
    path: '__user__/sci_data'
  __CyVerse__:
    system: 'data.iplantcollaborative.org'
    home: '/iplant/home'
    path: '__user__/sci_data'
  __sorghumDB__: 
    system: 'sciapps.org'
    home: '/agave_data'
    path: 'data/sorghum'
  __MaizeCODE__:
    system: 'sciapps.org'
    home: '/agave_data'
    path: 'data/maize'
  __exampleData__:
    system: 'sciapps.org'
    home: '/agave_data'
    path: 'example_data'
  __system__:
    system: ''
    home: ''
    path: ''
  __output__:
    system: 'sciapps.org'
    home: '/agave_data'
    path: 'results'
datastore_types: ['CyVerse', 'exampleData']
uncompress_suffix: '.open.tar.gz'
irodsEnvFile: '/usr/share/httpd/irodsEnv'
appsLocalCache: 0
defaultAppsList: 'public/assets/agaveAppsList.json'
queue_length: 3
