# configuration file for production environment
port: 80

# only log warning and error messsages
log: "warning"

# log message to a file in logs/
logger: "file"

# don't consider warnings critical
warnings: 1

# hide errors 
show_errors: 1

# cache route resolution for maximum performance
route_cache: 1

# For debugging
#log: "core"
#logger: "console"
#warnings: 1
#show_errors: 1

# production config
agave_config: ".agave"
host_url: "https://www.sciapps.org"
archive_system: 'data.iplantcollaborative.org'
archive_home: '/iplant/home'
archive_path: '__user__/archive/jobs'
input_system: 'brebiou.cshl.edu'
input_home: '/agave_data'
input_path: 'inputs'
email: 'noreply@sciapps.org'
upload_suffix: ".upload"
wf_step_prefix: 'wf_step_'
maxRunTime: "96:00:00"
datastore:
  __CyVerseUserData__: 
    system: 'data.iplantcollaborative.org'
    home: '/iplant/home'
    path: '__user__'
  __CyVerseSharedData__:
    system: 'data.iplantcollaborative.org'
    home: '/iplant/home'
    path: 'shared'
  __ArchivedJobs__: 
    system: 'data.iplantcollaborative.org'
    home: '/iplant/home'
    path: '__user__/archive/jobs'
  __exampleData__:
    system: 'sciapps.org'
    home: '/agave_data'
    path: 'example_data'
  __system__:
    system: ''
    home: ''
    path: ''
datastore_types: ['ArchivedJobs', 'CyVerseSharedData', 'CyVerseUserData', 'exampleData']
uncompress_suffix: '.open.tar.gz'
irodsEnvFile: '/usr/share/httpd/irodsEnv'
